import { FC, JSX, PropsWithChildren } from 'react';
import Head from 'next/head';

const Meta: FC<PropsWithChildren<{title: string}>> = ({children, title = 'NextApp'}): JSX.Element => {
  return (
    <Head>
      <title>{`${title} | Next.js Course`}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      {children}
    </Head>
  );
};
export default Meta;
